init:
  - git config --global core.autocrlf input

install:
  - choco install strawberryperl -version 5.20.1.1
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cpanm -n App::cpm
  - cpm install

build: off

test_script:
  - prove --norc --rc=.proverc -r t

cache:
  - local_action

shallow_clone: true
